rvm:
  - 1.9.3

branches:
  only:
    - master

bundler_args: --deployment

git:
  depth: 10

env:
  global:
  matrix:
    - CMD='bundle exec ruby test/spec_trimmer_controller.rb'

notifications:
  email: false

script: "$CMD"

source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBck9BYXE4eVBiV0Zobng2ajlxUGhhdEUrVGh4MXRodHc4RzdxTExNZlhXZk9oeWJxCmtuYUlJcFovS00xd1VBa1l2d2diTS9BWWM2SDluNlhzcWR4SEZzeHVOSEJzTlZNMmRHN1FmN252c0N5aXBIWFAKSWRhUWlmeWVYNEx1OTFBUjdVQy9OVlBBWUhSMjVqNzBJQS9YbUlqSHBNRmZpVGdjOFlVVWkzcjZpTUw4Q1JlZwovRmMxZVBvdnBjMkZBRUc0ZmYweFpsSjVjREsraXRwVlFxZlhMMWkvV2c3VWEvWWx4YzNRZ25wdzNyektMN3VJCmg2Slo5aUlUL3N5OGRPUGg4cVVRMWtLT1RjZEtDNExDYkJsMEQ1bzNxcVRaWitaeTZNTFJhRjhVZitVRkxEQkkKQURvQUtZKzlLYTNIekVlOGYrNnlaR3U2RWFZZE1Cd3RrNUJVbFFJREFRQUJBb0lCQVFDV3M2b3NkOS9VZjE3bApvb1ZXM2RnRkVURmFVSThBMkgwazY5dXlhZGYreWg2TlRReVI3MGlQdGxoVmpubkpHNVQ1K3l3VG84cjlDb3NaCklFRG1kb04yU1hJTXZyQmw4QXQ1aHB5MXE3WmFBeDhwZFJYREx0UERwbmU5VlZ2U05uZmFObVk1SzdCNXBTMTkKWEFYZTZWQ054VGNjMWdIZGtoQVJMMjBRaG4xZXVBUzQ3WXR4NE0wQ1FGYWZnUDVaSU92S2VycGN0Wk1heFZmagprNUtrNHYrZFUwL08yS25CSllLTGtTdXphdHZ2ZVBGYjRhOHNYSFNBSkJiajFRL1pNa2ExNnhzeStMUkZoM1M3Cmg1NGhXbVAxVGU0aDdXUC82elo3SldjK1dxRStkY1pleVJIT0J2R3NhT20yV1dRODYvNzFzQnl6ZFlUekJLak0KcTRBa2ZmYmhBb0dCQU5hbDNoWFRsWHNsYnVWMjU3WTBrdDVwU255L2VpbFY3SDRTeUIraWlaNm9jV0I2SWxzeQovMUtyT2g1TUZYbXhzaC8xd0JwV29IQXdrQUhBdlYxNmx1U0VVaGs3aW9FUVk0dlVkMG1qVUhSalpqdGxsZDVVCmZrMnhqdlVHekxuSXltS0lFVlpxbXkwTHR4aGNZOEpjVkx0ZWlKcDV0cWgrWnpDQzdzNzFaeUhkQW9HQkFNNHUKRTBVeVVXVmFyMlhONmdablJ4SEZ4TVlEYlAyeE92OU1lb1A4WkJYUTlMcEh6WklCNUhEVkN3dGt6MUdlRjNJQQpKWWROWjZCY3pLQyt6Q0NMTlg4eW81Q3VlYzVZTEdGRmlmOHk2d240b1Z2RnY1eENDTS9TS2FFUVRUaEsxeGhUCll0Qk4zU29xZ0pSWjZ3M2tNNUR4WGcyS2VVOGtCK2RzWUkwM0RMNFpBb0dBY2xrQWU3NHcxdDYxT2piaTc3VUkKUE1YNHNZWkw3UE5pUGpPQk95RWFrVlFJdWkyMldjRk1OVjBVWkFtQ00wZFByaWo4QXN2OVFtY01nSEtPTHR0Ywp3VFlnaW1LbXdXVGFzeVludWludmRXRnlsOWZoUkFUZEdFU3I5S3AvcThWazA2TExJYTgvSlhzbE9pd1YxUGZkCkI4Z3ZtNk9WaENONmsyUmRGaEd6dEYwQ2dZRUFrU1FnVHFyd1g5QXAveG1vc0I5T0NYWFdZcXFRdERwcVZNUksKenRVQ3c5VFlJclpmUVhSeGt2aDJrT3ZEZ2lvdlNRSlBhT01WbXU4WTRlUE9vTzQrbDY5WE00ZVBtYkc2ZEROVwp4TDdjZEtXQk9iQ0loWUI2NFltSjRxY3VKUDJTVTc2SHBpbmFFay9mT2cvZWgyWG80eFQyNThOZVNGY045VnoyCnp4STh0eWtDZ1lCeEFNb09nSXFWU1VySmJPRDBCNmtpMlpyTGdoVk5zVnltTk42WkRiZlNadmkxRjMrOG5VeWoKUUVsV3JUTzVQaGRTdEZxR3h5RHMxbDVCTUtQdXJQWHBGSGFkL2xxNDhhRURFbFN0WHp4eVE0d1lQSXhsVjNsQQpONFhnMUR4cWZUdzFCSU5wS2grVHh1WUFqSEZFTTNRTzZzK0RaaDI1MUw1KzBqOGYvaHFmNVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

